# Generated by Django 6.0.2 on 2026-03-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, default='profiles/default.webp', null=True, upload_to='profiles/'),
        ),
    ]
